<a href="https://colab.research.google.com/github/panda-sai/Gender-Prediction-Indian-Names-Dataset/blob/master/Gender_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from google.colab import files

In [3]:
female = files.upload()

Saving Indian-Female-Names.csv to Indian-Female-Names.csv


In [4]:
male = files.upload()

Saving Indian-Male-Names.csv to Indian-Male-Names.csv


In [0]:
dfmale = pd.read_csv('Indian-Male-Names.csv')
dffemale = pd.read_csv('Indian-Female-Names.csv')

In [7]:
dffemale.head()

name gender    race
0          shivani      f  indian
1             isha      f  indian
2  smt shyani devi      f  indian
3            divya      f  indian
4            mansi      f  indian

In [8]:
dfmale.head()

name gender    race
0          barjraj      m  indian
1     ramdin verma      m  indian
2  sharat chandran      m  indian
3  birender mandal      m  indian
4             amit      m  indian

In [0]:
gender = {'m': 1,'f': 0}
dfmale.gender = [gender[item] for item in dfmale.gender]
dffemale.gender = [gender[item] for item in dffemale.gender]

In [11]:
dfmale.head()

name  gender    race
0          barjraj       1  indian
1     ramdin verma       1  indian
2  sharat chandran       1  indian
3  birender mandal       1  indian
4             amit       1  indian

In [12]:
dffemale.head()

name  gender    race
0          shivani       0  indian
1             isha       0  indian
2  smt shyani devi       0  indian
3            divya       0  indian
4            mansi       0  indian

In [29]:
dfmale.drop(columns=['race'])
dfmale.head()

name  gender
0          barjraj       1
1     ramdin verma       1
2  sharat chandran       1
3  birender mandal       1
4             amit       1

In [0]:
dffemale = dffemale.drop(columns=['race'])

In [33]:
dffemale.head()

name  gender
0          shivani       0
1             isha       0
2  smt shyani devi       0
3            divya       0
4            mansi       0

In [0]:
df = pd.concat([dfmale,dffemale])

In [36]:
df

name  gender
0                        barjraj       1
1                   ramdin verma       1
2                sharat chandran       1
3                birender mandal       1
4                           amit       1
...                          ...     ...
15377                 saroj devi       0
15378              naina @ geeta       0
15379  manju d/0 baboo lal jatav       0
15380                    shivani       0
15381                      nayna       0

[30227 rows x 2 columns]

In [0]:
dffinal = df.sample(frac=1)

In [38]:
dffinal.head()

name  gender
10297    vishal panchal       1
10748            sanjay       1
8607             shaira       0
3312            sushila       0
2079   kali charan sain       1

In [40]:
print(df.size)
print(dffinal.size)

60454
60454


In [0]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import DictVectorizer

In [0]:
names = dffinal['name']

In [43]:
names

10297           vishal panchal
10748                   sanjay
8607                    shaira
3312                   sushila
2079          kali charan sain
                 ...          
8028                    netram
3575                 gauravgil
12430                  gulista
7559     birender kishor bhala
4818                    preeti
Name: name, Length: 30227, dtype: object

In [45]:
names[0]

0    shivani
0    barjraj
Name: name, dtype: object

In [0]:
cv = CountVectorizer()
X = cv.fit_transform(names.values.astype('U'))

In [51]:
cv.get_feature_names()

['02',
 '105',
 '11',
 '16',
 '18',
 '1957975',
 '1st',
 '20',
 '21',
 '24',
 '25',
 '27',
 '28',
 '33',
 '330',
 '341',
 '35',
 '3rd',
 '3yrs',
 '4yrs',
 '629',
 '66',
 '6month',
 '72',
 '7206252659',
 '7404660980',
 '773',
 '78',
 '8295508258',
 '86',
 '8901040854',
 '95',
 '9813186044',
 '9yr',
 'aabid',
 'aabida',
 'aachal',
 'aadesh',
 'aadil',
 'aadish',
 'aaditya',
 'aaenab',
 'aafreen',
 'aafrin',
 'aaftaab',
 'aaftab',
 'aagad',
 'aagand',
 'aahim',
 'aahuja',
 'aajad',
 'aajam',
 'aajiv',
 'aakanksha',
 'aakar',
 'aakas',
 'aakash',
 'aakhon',
 'aakib',
 'aakil',
 'aalabndi',
 'aalam',
 'aale',
 'aalina',
 'aaliya',
 'aamil',
 'aamin',
 'aamina',
 'aamir',
 'aamliya',
 'aamna',
 'aamod',
 'aamosh',
 'aamrin',
 'aanad',
 'aanamika',
 'aanand',
 'aanchal',
 'aanik',
 'aanil',
 'aansi',
 'aansu',
 'aanu',
 'aanya',
 'aapa',
 'aapu',
 'aaqif',
 'aara',
 'aaradhana',
 'aarati',
 'aarav',
 'aardhna',
 'aarif',
 'aarifa',
 'aarifun',
 'aariv',
 'aarju',
 'aarsi',
 'aarti',
 'aarushi

In [0]:
Y = dffinal.gender

In [0]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [54]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [55]:
model.score(x_test,y_test)

0.9104761904761904

In [0]:
sample = ["sai"]
vector = cv.transform(sample).toarray()

In [57]:
model.predict(vector)

array([0])

In [0]:
sample1 = ["panda sai sankara kesava nath"]
vector1 = cv.transform(sample1).toarray()

In [59]:
model.predict(vector1)

array([1])

In [0]:
sample2 = ["panda krishna vamsi nath"]
vector2 = cv.transform(sample2).toarray()

In [61]:
model.predict(vector2)

array([1])

In [0]:
sample3 = ["moulika"]
vector3 = cv.transform(sample3).toarray()

In [71]:
model.predict(vector3)

array([0])

In [0]:
sample4 = ["bhavani"]
vector4 = cv.transform(sample4).toarray()

In [69]:
model.predict(vector4)

array([0])